# BUILD
FROM microsoft/aspnetcore-build:2 AS builder

# caches restore result by copying csproj file separately
COPY . /src

WORKDIR /src/Europa.Web.Tests
RUN dotnet restore
RUN dotnet test

WORKDIR /src/Europa.Services.Tests
RUN dotnet restore
RUN dotnet test

WORKDIR /src/Europa.Data.Tests
RUN dotnet restore
ENTRYPOINT ["dotnet", "test"]